### ISSUE TITLE
iOS Build error with Cordova 6.0.0

### ISSUE THREAD

**Issue by gcollazo** [adnathan/ace#18]
Just started a new Cordova project to test Ace and had issues building the project for iOS.
- `cordova create hello`
- `cordova platform add ios`
- `cordova plugin add cordova-plugin-ace`
- `cordova build ios`

```
Error: Error code 65 for command: xcodebuild...
```

Then I tried to run the project directly from xcode and noticed the following error.
<img width="246" alt="screen shot 2016-03-01 at 10 39 48 pm" src="https://cloud.githubusercontent.com/assets/61048/13449093/8704f8b0-dffe-11e5-8c88-410591d6ecd6.png">

I then changed the import from:

``` objc
#import "../../../CordovaLib/Classes/CDVViewController.h"
```

to:

``` objc
#import "../../../CordovaLib/Classes/Public/CDVViewController.h"
```

This fixed the build.

**Comment by bwhitty** [comment]
I get the same error on 6.0.0

```
CompileC build/HelloWorld.build/Debug-iphonesimulator/HelloWorld.build/Objects-normal/i386/AcePluginManager.o HelloWorld/Plugins/cordova-plugin-ace/AcePluginManager.mm normal i386 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
...
...
/some/path/cordova/hello/platforms/ios/HelloWorld/Plugins/cordova-plugin-ace/AcePluginManager.mm:6:9: fatal error: '../../../CordovaLib/Classes/CDVViewController.h' file not found
#import "../../../CordovaLib/Classes/CDVViewController.h"
        ^
1 error generated.
```

**Comment by adnathan** [comment]
Thanks for the report! I believe I have fixed it with the referenced commit just now. Let me know if you still run into problems!
