### ISSUE TITLE
how to invoke javascript function from native code ?

### ISSUE THREAD

**Issue by ddouble** [adnathan/ace#21]
how to invoke javascript function from native code ?

or how to “fire event” from native code, and listen it from native code ?

**Comment by adnathan** [comment]
Great question!  There is a way, currently used by the cross-platform UI objects that raise events, but the API could use some polishing.  On Android:

`run.ace.OutgoingMessages.raiseEvent("myevent", nativeInstance, simpleArgument);`

On iOS (when importing OutgoingMessages.h):

`[OutgoingMessages raiseEvent:@"myevent" instance:nativeInstance eventData:simpleArgument];`

Subscribing in JavaScript:

`var instance = new ace.NativeObject("ClassWithEvent");`
`instance.addEventListener("myevent", function(sender, arg) { });`

Let me know if you run into any issues!
