### ISSUE TITLE
Styling and Dynamic Content

### ISSUE THREAD

**Issue by nasimoyz** [adnathan/ace#22]
Hey there, I'm sorry if this isn't the right place to post these types of questions, but didn't know how else to get in touch and am wanting to do some things that aren't yet in the docs.
1. In the styling doc page (http://microsoft.github.io/ace/docs/styling/) you mention some of the “common visual properties”. I was wondering if there was a comprehensive list anywhere? We’re interested in being able to implement common CSS styling, things like: apply background images to containers, rounded-edges (border-radius), add padding to backgrounds, apply borders, etc.
2. Is it possible to add dynamic content to the page - for example, a timer element which continuously counts up? This is the one we’re using currently in HTML, but seek to implement a similar on in Ace: https://siddii.github.io/angular-timer/

Thanks for the great work you’ve done on Project Ace! Looking forward to hearing from you.

**Comment by ztl8702** [comment]
For the second part: is it hard? Could you just use javascript like to change the text of a native element?
