### ISSUE TITLE
WebView not working on Android

### ISSUE THREAD

**Issue by krik** [adnathan/ace#23]
Hello! 

I'm experimenting with Ace at the moment, specifically I'm trying to recreate the cordova in app browser. I took some inspiration from the examples/WithPlugins/InAppBrowser project. Also I saw that Ace provides its own WebView control. I'm running into problems with the latter though.
- Android 4.4 and 6.0 (Genymotion)
- cordova-android 4.1.1
- cordova-plugin-ace 0.0.14

I get the following error when trying to initialize the WebView using JavaScript: 

```
 var webview = new ace.WebView();
```

```
D/Ace     ( 2818): Caught exception: java.lang.RuntimeException: Unable to find a class named 'Windows.UI.Xaml.Controls.WebView'
D/Ace     ( 2818):  at run.ace.IncomingMessages.create(IncomingMessages.java:50)
D/Ace     ( 2818):  at run.ace.NativeHost$2.run(NativeHost.java:234)
D/Ace     ( 2818):  at android.os.Handler.handleCallback(Handler.java:733)
D/Ace     ( 2818):  at android.os.Handler.dispatchMessage(Handler.java:95)
D/Ace     ( 2818):  at android.os.Looper.loop(Looper.java:136)
D/Ace     ( 2818):  at android.app.ActivityThread.main(ActivityThread.java:5001)
D/Ace     ( 2818):  at java.lang.reflect.Method.invokeNative(Native Method)
D/Ace     ( 2818):  at java.lang.reflect.Method.invoke(Method.java:515)
D/Ace     ( 2818):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
D/Ace     ( 2818):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
D/Ace     ( 2818):  at dalvik.system.NativeStart.main(Native Method)
I/chromium( 2818): [INFO:CONSOLE(310)] "Error in Error callbackId: NativeHost1388986910 : Error: Native error: java.lang.RuntimeException: Unable to find a class named 'Windows.UI.Xaml.Controls.WebView'
```

**Comment by BreixoAM** [comment]
Have the same problem, for some reason the plugin installation fail to copy WebView.java on the platform directory.

To fix the problem i just create this file: platforms/android/src/run/ace/framework/WebView.java

With this content:

//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
package Windows.UI.Xaml.Controls;

import android.view.ViewGroup;
import android.widget.AbsoluteLayout;

public class WebView extends android.webkit.WebView implements IHaveProperties {

```
public WebView(android.content.Context context) {
    super(context);
}

// IHaveProperties.setProperty
public void setProperty(String propertyName, Object propertyValue) {
    if (propertyName.equals("WebView.Source")) {
        this.loadUrl((String)propertyValue);
    }
    else if (!ViewGroupHelper.setProperty(this, propertyName, propertyValue)) {
        throw new RuntimeException("Unhandled property for " + this.getClass().getSimpleName() + ": " + propertyName);
    }
}
```

}

**Comment by krik** [comment]
Thanks for the tip, turns out the reference for the source file is simply missing in plugin.xml!
