### ISSUE TITLE
Error when building with XCode 7.3 

### ISSUE THREAD

**Issue by krik** [adnathan/ace#25]
When building with Xcode 7.3 I get the following error after I add the plugin to a project: 

```
**/Plugins/cordova-plugin-ace/WebView.mm:48:11: error: cannot initialize an exception object of type
      '<pseudo-object type>' with an rvalue of type 'NSString *'
    throw error.description;
```
- cordova-ios 3.9.2 or cordova-ios 4.1.1
- cordova-plugin-ace 0.0.14

**Comment by Patrick-Ullrich** [comment]
Same, unable to run example due to this error.

**Comment by adnathan** [comment]
Thanks for your report and your patience! This is now fixed.
