### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by orangecoloured** [adnathan/ace#30]
I really liked the idea of having native UI using cordova. I've never used XAML before.
And I was a bit disappointed about not being able to use it on Linux.
So the only option is to have all the UI generated with JS.
But I find the documentation a bit confusing.

For example I need to make a button. I need to position it, to change style and content. But the docs [here](http://microsoft.github.io/ace/docs/ref/#two) have nothing on those methods. And there are some examples [here](http://microsoft.github.io/ace/docs/styling/) in styling section.

Did I look in the right place? =)
Is there a better way getting to know ace?

**Comment by axemclion** [comment]
@orangecoloured XAML is one way of defining the UI. At the moment, we are exploring alternative ways to define the UI - people have told us that XAML may not be their preferred language. 

Would you prefer something like Ionic's HTML like markup instead ?

**Comment by orangecoloured** [comment]
HTML would be a nice thing for web-developers. If this is your target group with ace then probably yeah.
Not sure about all the caveats here. I don't mind generating the UI with JS or any other way, my only concern here is the documentation.

**Comment by adnathan** [comment]
You are correct that the documentation is minimal at the moment. You position elements depending on the layout panel, so the documentation for that is at http://microsoft.github.io/ace/docs/layout/. Styling is indeed described at http://microsoft.github.io/ace/docs/styling/. And you set content with a control's setContent method. I'll add some pointers and info to that reference page, so hopefully that will help.
