### ISSUE TITLE
Callback from iOS to JS

### ISSUE THREAD

**Issue by liangqiangkun** [adnathan/ace#31]
In my item, I have assembled the cordova plugin that works a treat. Eventually I have successfully achieved the way of writing iOS code at the part of JS. However,I find a serious problem that "Call native code " does not realize the callback from native to JS. Sincerely I wish your company support us in technology.

**Comment by ztl8702** [comment]
I think the maintainer @adnathan is probably on a leave or taking a break, because he has no activities on GitHub for quite a long time. And I think this project is more of a personal project than a Microsoft-supported project. Still, I look forward to @adnathan responding to the community and we can build this project together.

**Comment by axemclion** [comment]
@ztl8702 Project ACE is still an experiment, and we are looking at ways to ensure that ACE is presented in its best form for people to use. 

One thing that people have told us is that they may just need the capability to draw Native UI. We are considering separating the ability to create Native UI, and the ability to call Native APis into separate plugins.

@ztl8702 Would you be interested in talking to us (over phone/skype, etc) as to how you see using ACE, or even using Native UI/Native APIs ?

**Comment by adnathan** [comment]
@liangqiangkun, does my response to issue #21 help you?  If that mechanism works for you, we could certainly present the API in a less cumbersome way.  Thanks!

**Comment by ztl8702** [comment]
@axemclion Thanks for the reply. Yeah I'd love to have a talk about this.

**Comment by liangqiangkun** [comment]
@adnathan Thank you very much,it works ,I will continue to focus on the use of ACE.
