### ISSUE TITLE
Canvas/WebGL with this plugin?

### ISSUE THREAD

**Issue by jdnichollsc** [adnathan/ace#32]
Hi guys,

What do you think about use WebGL/Canvas with this plugin?

See my example using Ionic Framework: http://market.ionic.io/plugins/ionphaser

Regards, Nicholls

**Comment by adnathan** [comment]
You could certainly do that (and hopefully the two plugins can play nicely together).  The primary focus for this plugin is on native UI that isn't hosted in the WebView, but there's no reason you can't use WebGL/Canvas in the WebView portion of an app.

**Comment by jdnichollsc** [comment]
Thanks, let me check! :dancers:
