### ISSUE TITLE
Widgets API?

### ISSUE THREAD

**Issue by ojoanalogo** [adnathan/ace#33]
Hello, i've seen the example provided in the PhonegapDay APP, and also the example in the widget documentation but i only see how to add text to a list based widget. 
Does it's possible to make more advanced widgets? I would like to add a schedules widget, showing the day name and a few images on it but i can't find any examples or methods to do this.
Thanks

**Comment by adnathan** [comment]
Hi! The helper APIs are indeed just for adding text right now. However, nothing prevents you from writing an arbitrarily-complex widget. You just need to do it as if you were writing a native app and have some amount of logic in Java. You can then interoperate between your JavaScript and your Java using more generic Ace features. Does that make sense? You can see how the current widget APIs work on the Java side in the src/android/appwidgets folder.

**Comment by ojoanalogo** [comment]
Thanks for the response, i've got a few things working for custom widgets just as you described :)
