### ISSUE TITLE
Xamarin and Ionic?

### ISSUE THREAD

**Issue by jdnichollsc** [adnathan/ace#34]
Hi guys!

Is possible integrate Xamarin with Ionic Framework using this plugin? :ocean: 

Regards, Nicholls

**Comment by adnathan** [comment]
Hi!  Nothing currently in this plugin really enables that.  The UI Framework and the XAML you can optionally use looks just like it does for UWP, so it also looks similar to what you would do with Xamarin, but it is independent.

**Comment by jdnichollsc** [comment]
Interesting, thanks!

**Comment by adnathan** [comment]
I'm going to close this issue now.  Please reopen if you need more info!
