### ISSUE TITLE
Doesn't work with Cordova Lib 4.0.1+

### ISSUE THREAD

**Issue by wmkeicher** [adnathan/ace#35]
index.html does not load when using Cordova Lib 4.0.1.+ in iOS

From what I can tell this is because of Cordova changes to CDVUIWebViewNavigationDelegate.m::shouldStartLoadWithRequest
https://github.com/apache/cordova-ios/blob/f75bf67438257132e739238ed579d73271b3a716/CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewNavigationDelegate.m

A potential fix might be to change the value returned by NativeHost.mm's shouldOverrideLoadWithRequest:navigationType method

**Comment by jmiller14** [comment]
I am having the same issue -- had to downgrade cordova-ios to 3.9.2

**Comment by adnathan** [comment]
Thanks for the report!  I will look into this.
