### ISSUE TITLE
Add button to title bar?

### ISSUE THREAD

**Issue by wmkeicher** [adnathan/ace#36]
Hi,

Is it possible to add a button to the title bar?  I've only been able to add buttons to the bottom of the page.

`
var page = new ace.Page();
                var commandBar = new ace.CommandBar();
                var appBarButton = new ace.AppBarButton();
                appBarButton.setLabel("test");
                commandBar.getPrimaryCommands().add(appBarButton);
                page.setCommandBar(commandBar);
                page.setTitle("Title");
                page.setContent(ace.getHostWebView());
                ace.getHostPage().setContent(page);
`

**Comment by frederikbosch** [comment]
See #38, contains fix for top app bar via javascript.

``` js
var commandBar = new ace.CommandBar();
var button = new ace.AppBarButton();
button.setLabel('Button');
commandBar.getPrimaryCommands().add(button);

page.setTopAppBar(commandBar);
```
