### ISSUE TITLE
Cannot set title on the main page in Android

### ISSUE THREAD

**Issue by frederikbosch** [adnathan/ace#37]
```
05-06 20:18:14.995 12707 12707 I chromium: [INFO:CONSOLE(310)] "Error in Error callbackId: NativeHost1158829928 : Error: Native error: java.lang.RuntimeException: Error setting FrameLayout's UserControl.Content to Windows.UI.Xaml.Controls.Page{d535279 V.E...... ......I. 0,0-0,0}
05-06 20:18:14.995 12707 12707 I chromium:      at run.ace.IncomingMessages.set(IncomingMessages.java:206)
05-06 20:18:14.995 12707 12707 I chromium:      at run.ace.NativeHost$2.run(NativeHost.java:239)
05-06 20:18:14.995 12707 12707 I chromium:      at android.os.Handler.handleCallback(Handler.java:739)
05-06 20:18:14.995 12707 12707 I chromium:      at android.os.Handler.dispatchMessage(Handler.java:95)
05-06 20:18:14.995 12707 12707 I chromium:      at android.os.Looper.loop(Looper.java:148)
05-06 20:18:14.995 12707 12707 I chromium:      at android.app.ActivityThread.main(ActivityThread.java:5422)
05-06 20:18:14.995 12707 12707 I chromium:      at java.lang.reflect.Method.invoke(Native Method)
05-06 20:18:14.995 12707 12707 I chromium:      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-06 20:18:14.995 12707 12707 I chromium:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-06 20:18:14.995 12707 12707 I chromium: Caused by: java.lang.RuntimeException: Cannot set title on the main page in Android unless you set <preference name="ShowTitle" value="true"/> in config.xml.
05-06 20:18:14.995 12707 12707 I chromium:      at run.ace.TabBar.setTitle(TabBar.java:39)
05-06 20:18:14.995 12707 12707 I chromium:      at Windows.UI.Xaml.Controls.Page.updateTitle(Page.java:67)
05-06 20:18:14.995 12707 12707 I chromium:      at Windows.UI.Xaml.Controls.Page.processBars(Page.java:75)
05-06 20:18:14.995 12707 12707 I chromium:      at Windows.UI.Xaml.Controls.ViewGroupHelper.setProperty(ViewGroupHelper.java:51)
05-06 20:18:14.995 12707 12707 I chromium:      at run.ace.IncomingMessages.set(IncomingMessages.java:191)
05-06 20:18:14.995 12707 12707 I chromium:      ... 8 more
```

Already found [this thread on StackOverflow](http://stackoverflow.com/questions/35689252/use-ace-plugin-to-make-ios-android-tabbar-tableview-using-platform-specific-ja) but that does not help me finding the solution. I tried uppercase/lowercase `ShowTitle` in the config.xml, both in android specific config and global config. It just won't work. Do you have any idea?

**Comment by frederikbosch** [comment]
Now, even commenting the `setTitle` line does not seem to help. So I am not setting a title at all, but I am still receiving the error?!

**Comment by frederikbosch** [comment]
It has to with the android build. Apps built by Phonegap do not suffer from this error, while my `cordova run android` are failing.

**Comment by frederikbosch** [comment]
Actually I think this is a documentation issue. Since Phonegap does build this app, I should replicate its behaviour/settings locally. But that means, there are certain unmentioned criteria that have to be taken care of before you can use `cordova run android`.

**Comment by rliang** [comment]
Looks like a problem with the `cordova-android` platform.

When running `cordova prepare`, the generated `platforms/android/AndroidManifest.xml` contains `android:theme="@android:style/Theme.DeviceDefault.NoActionBar"` regardless of the `ShowTitle` config.

AceExamples cleverly avoids this by overriding it in `native/android/AndroidManifest.xml`, and thus doesn't have this problem. Too bad this isn't documented...

**Comment by frederikbosch** [comment]
@rliang Many thanks for clearing this. I created a PR that fixes this automatically!

**Comment by frederikbosch** [comment]
Thanks @adnathan !
