### ISSUE TITLE
Unity3D+Ace or Godot+Ace ?

### ISSUE THREAD

**Issue by ghost** [adnathan/ace#42]
Hi guys,

Hope you are doing all well !

I was testing your great repo, and I was wondering if there is any example integrating ACE+Unity3D in a native view. That would be awesome.

More widely, I was wondering if the Ace Plugin would be suitable to mix such kind of integration without having too much memory leaks due to the bridging.

But definitely, it would be great to get more advanced examples for ACE. 

Thanks in advance for your reply or point of view :-).

Cheers,
Luc

**Comment by jmatthiesen** [comment]
Thanks for your feedback! Please note that we're no longer maintaining this repo. Here's the official notice, copied from our readme:

As of December 2016, this project is no longer maintained by Microsoft. We built ACE to provide developers with an “escape hatch” to access native code from within JavaScript. After nearly a year in production, we learned that most developers are satisfied with the access granted by Cordova’s Plugin Model. Thus, we’ve discontinued active development. We appreciate your interest in the project and hope you found it exemplary of Microsoft’s commitment to experimentation and open source software. if you're interested in continuing this project, please feel free to fork it. As of December 2016, we will no longer monitor or respond to open issues. You can keep up with other projects from Microsoft’s Cordova team by visiting http://taco.visualstudio.com. Thanks for your support!
