### ISSUE TITLE
Screen rotation problem

### ISSUE THREAD

**Issue by efistokl** [adnathan/ace#48]
Hello
We're developing X-platform app using your plugin.
But we have faced a problem in iOS:

Initially, our app disallowed lanscape mode. User could only use it in portrait mode.
But after adding cordova-plugin-ace this restriction was somehow bypassed....

So, we want to somehow get this restriction back to work. (This happens only in iOS, Android works as before)

Thank You in advance

Some details about usage of your plugin: we have a Popup with AceWebView inside. (Something like internal browser in facebook app)

**Comment by efistokl** [comment]
I've just muddled through. I've modified plugin adding [this](http://stackoverflow.com/questions/11785565/how-can-i-disable-landscape-orientation/11785618#11785618) to AceViewController.mm and AceNavigationController.mm. (modified both because i'm not sure which controller is responsible for the whole app)

**Comment by adnathan** [comment]
Thanks for the report, and I'm glad you found a workaround.  I'll look at changing both to respect the app's settings.  AceNavigationController is always relevant when Ace is used.  AceViewController is used for additional native pages (if any).
