### ISSUE TITLE
Cordova opens about:blank upon using this plugin on iOS app 

### ISSUE THREAD

**Issue by sushruth** [adnathan/ace#50]
I tried to use this plugin (with zero custom configuration and out of the box) with a cordova app I already have, it breaks the app and Cordova can only opens about:blank and index.html is not accessable. I see no error messages in system log for the device. As soon as i remove this plugin the app starts working. This is specific ONLY to iOS.

Is anyone else facing this issue ?

EDIT : Confirmed on fresh cordova starter app too. Adding this plugin leads to cordova opening up `about:blank` instead of the url to `index.html`
##### Edits to list solutions found online which did not work :

[EDIT](https://forum.ionicframework.com/t/showing-blank-white-screen/15545/46) : Adding  `<allow-navigation href="*" />` to `config.xml` did not work

EDIT : Fixed in version 0.0.16

**Comment by sushruth** [comment]
Found a solution : Adding the following line to `config.xml` will solve the issue.

```xml
<allow-navigation href="*" />
```

Leaving this here just in case anyone has the same issue.

**Comment by adnathan** [comment]
This sounds like issue #35, recently fixed.  If you're getting the plugin from NPM, then the fix wasn't there yet.  I just pushed version 0.0.16.  Can you try adding the plugin again and ensuring you have this version?  Thanks!

**Comment by eljefedelrodeodeljefe** [comment]
I am also having this issue. Adding the plugin to an existing project will also lead to a spinner not disappearing. Running a on android seems fine though.

**Comment by sushruth** [comment]
It worked. Thanks a lot!

**Comment by eljefedelrodeodeljefe** [comment]
What exactly did you do?

**Comment by sushruth** [comment]
I just did `cordova plugin remove cordova-plugin-ace` and then a `cordova plugin add cordova-plugin-ace` again. It worked.

**Comment by eljefedelrodeodeljefe** [comment]
Okay seems to be resolved now for me too. Thanks!
