### ISSUE TITLE
Tags/Releases

### ISSUE THREAD

**Issue by efistokl** [adnathan/ace#52]
Hello @adnathan,

It will be wonderful If you add tags to some of your commits. (To prevent unexpected build failures caused by some new changes in plugin)
If you do this, we'll be able to stick to the specified version of your plugin.

Thank You very much.

**Comment by adnathan** [comment]
I will do that.  Stay tuned.  Thanks!

**Comment by adnathan** [comment]
I've made a 0.1.0 release that includes the fix for the __CORDOVA_4_0_0 issue.  Let me know if you run into any more problems.  Thanks!
