### ISSUE TITLE
Promises instead of callbacks

### ISSUE THREAD

**Issue by pke** [adnathan/ace#60]
First, thumbs up for this project! It looks like magic :) I also like that it can potentially make a lot of cordova plugins obsolete (thinking of the device plugin) when you can now have very simple snippets only to directly call native API.

And that brings me to the biggest issue I see at the moment when looking at the code. Since all native calls are async they need to be nested in the default nodejs callback pattern. However the `Promise` pattern can achieve much better read-ability (if done right).

Do you think this project could be _promisified_ somehow?

**Comment by jdnichollsc** [comment]
+1

**Comment by frederikbosch** [comment]
I agree on this. However, we should take into account that there is no `babel` or other transpiler available. So we should leave our ES6 syntax home and write old school highly compatible javascript.

**Comment by jdnichollsc** [comment]
Maybe using Q promise or another library? https://github.com/kriskowal/q
