### ISSUE TITLE
start android activity through Ace

### ISSUE THREAD

**Issue by Paul-Lo** [adnathan/ace#62]
Is it possible to start my custom android activity through Ace?
If yes, how do we achieve it?

I've tried several days but can't achieve that.

Thanks.

**Comment by adnathan** [comment]
I just exposed the ace.android.startActivity API to JavaScript with commit 34199c4622caa34e685f8d41ba746d36ba63aee0.  Thanks!

**Comment by adnathan** [comment]
Note that the first activity still needs to be MainActivity (deriving from CordovaActivity).  You could modify the auto-generated code in MainActivity.java if you wanted to customize that.

**Comment by Paul-Lo** [comment]
Much appreciated, Adam.
