### ISSUE TITLE
Is this a toy project?

### ISSUE THREAD

**Issue by v3ss0n** [adnathan/ace#70]
No Response to issues , no updates. 
This have very huge potential , why stopped?

**Comment by Paul-Lo** [comment]
? I just saw there is update 14 days ago for the documentation. 
There is indeed updates.

**Comment by v3ss0n** [comment]
![nope](https://cloud.githubusercontent.com/assets/419606/18318801/1480074a-7549-11e6-8200-53a0d4c9b3a0.png)
`nope.png`

**Comment by hussainak** [comment]
hopefully this time its not typical Microsoft and hopefully we are not left in the limbo again

**Comment by frederikbosch** [comment]
This is open source. Instead of criticizing: do something and contribute! Enhance collaboration and make sure this is not a one man show. I already devoted part of my time; how about yours?

**Comment by v3ss0n** [comment]
Is there a roadmap?no
Is there responses to issues thses days? No

**Comment by frederikbosch** [comment]
Is there any pull request? No.

**Comment by hussainak** [comment]
Apologies, my post was not to offend anyone but to highlight typical Microsoft behaviour. Nothing against the employee mate! take it easy!

**Comment by v3ss0n** [comment]
@frederikbosch we will be more likely to devote our time if this project have its care from project owners. Like project plan , roadmap , and more response to issues.

For example we are not sure if the Floating UI is supported at all in the code base already. I grep the code and i can't find anything but `documentation coming soon` . 

Intimidation and holier than thou will not make anyone contribute more , will go opposite. But as @hussainak  mentioned , with all due respects,  i understand it as typical MS behavior.

**Comment by panarasi** [comment]
As indicated in the README.md, we have put out a statement that clarifies the current status of the project 

> As of December 2016, this project is no longer maintained by Microsoft. We built ACE to provide developers with an “escape hatch” to access native code from within JavaScript. After nearly a year in production, we learned that most developers are satisfied with the access granted by Cordova’s Plugin Model. Thus, we’ve discontinued active development. We appreciate your interest in the project and hope you found it exemplary of Microsoft’s commitment to experimentation and open source software. if you're interested in continuing this project, please feel free to fork it. As of December 2016, we will no longer monitor or respond to open issues. You can keep up with other projects from Microsoft’s Cordova team by visiting http://taco.visualstudio.com. Thanks for your support!

However, if you folks want to pick up the work on it, we would gladly support it and could look at giving you commit rights.
