### ISSUE TITLE
Get button inside xml layout

### ISSUE THREAD

**Issue by angjelkom** [adnathan/ace#72]
The doc says:
If you’re using Android XML, you can set ids as you normally would, and programmatically leverage those ids in JavaScript the same way you would in Java.

But I don't have any idea what he means by that I tried, root.findViewById, root.getId but nothing works, I want to get a button which is inside of the the root of this layout

ace.load("android://list_widget_item.xml", function (root) {
    // Attach event handler
    console.log(root)
});

**Comment by jmatthiesen** [comment]
As of December 2016, this project is no longer maintained by Microsoft. We built ACE to provide developers with an “escape hatch” to access native code from within JavaScript. After nearly a year in production, we learned that most developers are satisfied with the access granted by Cordova’s Plugin Model. Thus, we’ve discontinued active development. We appreciate your interest in the project and hope you found it exemplary of Microsoft’s commitment to experimentation and open source software. if you're interested in continuing this project, please feel free to fork it. As of December 2016, we will no longer monitor or respond to open issues. You can keep up with other projects from Microsoft’s Cordova team by visiting http://taco.visualstudio.com. Thanks for your support!
