### ISSUE TITLE
Make this project usable

### ISSUE THREAD

**Issue by denkomanceski** [adnathan/ace#73]
By the title I mean this: people are using a lot of different frameworks like Angular2, ReactJS etc.. Because of this, we cannot afford loading a different html page every time we want to navigate from one page to another (obv that app has a state already + these framework have some load time delay). It will be really awesome if somehow the native layer would be able keep the webview in memory (with the app already initialized) and than being able to present it wherever we want. If this kind of functionality is integrated with lets say the Angular2 router it would be awesome.. many people will add native modals, navbars, side menus to their pure Ionic app and make it smoother and better UX. Maybe someone can post some examples of how to integrate it in existing project that is using these new modern frameworks, than the project is viable and I am sure it gain many contributors in no time

**Comment by jmatthiesen** [comment]
Hi, @denkomanceski - thanks for the great feedback and interest here. Our team is no longer maintaining this repo, but I encourage anyone who's interested in forking it! Please see our official notice, just posted yesterday:

As of December 2016, this project is no longer maintained by Microsoft. We built ACE to provide developers with an “escape hatch” to access native code from within JavaScript. After nearly a year in production, we learned that most developers are satisfied with the access granted by Cordova’s Plugin Model. Thus, we’ve discontinued active development. We appreciate your interest in the project and hope you found it exemplary of Microsoft’s commitment to experimentation and open source software. if you're interested in continuing this project, please feel free to fork it. As of December 2016, we will no longer monitor or respond to open issues. You can keep up with other projects from Microsoft’s Cordova team by visiting http://taco.visualstudio.com. Thanks for your support!
