### ISSUE TITLE
Works with Crosswalk?

### ISSUE THREAD

**Issue by jdnichollsc** [adnathan/ace#8]
Hi man, about the documentation... This plugin support Crosswalk project? :dancers:

**Comment by adnathan** [comment]
This hasn't been tested, but it might work just fine! :)  If not, I'm guessing we can make them play nicely together.  I'll have to give it a try in the near future.

**Comment by ghost** [comment]
I just confirmed that Ace does work with the Crosswalk WebView. I added overlays and such and it works fine. The only issue I ran in to is with adding a header or footer. It looks like the Crosswalk webview is "hard coded" to take up the entire screen height and width. It assumes that it will always occupy 100% of screen real-estate. This seems like a legitimate assumption on their part. I will try to dig a little deeper in to the Crosswalk webview, as we are planning a similar use-case.

**Comment by frederikbosch** [comment]
Actually, it works perfectly with crosswalk. This ticket can be closed.

**Comment by jdnichollsc** [comment]
Cool
